# Use postgres/example user/password credentials
version: '2.1'

services:

  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      TZ: UTC
      POSTGRES_DB: gopolls
      POSTGRES_INITDB_ARGS: "--encoding=utf8"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
