version: '3.1'

services:
  pg:
    image: "postgres:13.0-alpine"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=exmaple
      - POSTGRES_DB=gopolls
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
